#cmakedefine SIZEOF_CHAR @SIZEOF_CHAR@
#cmakedefine SIZEOF_SHORT @SIZEOF_SHORT@
#cmakedefine SIZEOF_INT @SIZEOF_INT@
#cmakedefine SIZEOF_LONG @SIZEOF_LONG@

#define RETSIGTYPE void
#define WITH_BINKP 1

#cmakedefine STDC_HEADERS @STDC_HEADERS@
#cmakedefine HAVE_SYS_TYPES_H @HAVE_SYS_TYPES_H@
#cmakedefine HAVE_SYS_TIME_H @HAVE_SYS_TIME_H@
#cmakedefine HAVE_STDLIB_H @HAVE_STDLIB_H@
#cmakedefine HAVE_SYS_SOCKET_H @HAVE_SYS_SOCKET_H@
#cmakedefine HAVE_ERRNO_H @HAVE_ERRNO_H@
#cmakedefine HAVE_NETINET_IN_H @HAVE_NETINET_IN_H@
#cmakedefine HAVE_NETDB_H @HAVE_NETDB_H@
#cmakedefine HAVE_FCNTL_H @HAVE_FCNTL_H@
#cmakedefine HAVE_UTIME_H @HAVE_UTIME_H@
#cmakedefine HAVE_SYSLOG_H @HAVE_SYSLOG_H@
#cmakedefine HAVE_TERMIOS_H @HAVE_TERMIOS_H@
#cmakedefine HAVE_TERMIO_H @HAVE_TERMIO_H@
#cmakedefine HAVE_UNISTD_H @HAVE_UNISTD_H@
#cmakedefine HAVE_DIRENT_H @HAVE_DIRENT_H@
#cmakedefine HAVE_TIME_H @HAVE_TIME_H@
#cmakedefine HAVE_NCURSES_H @HAVE_NCURSES_H@
#cmakedefine HAVE_SYS_TIME_H @HAVE_SYS_TIME_H@
#cmakedefine HAVE_SYS_STAT_H @HAVE_SYS_STAT_H@
#cmakedefine HAVE_ARPA_INET_H @HAVE_ARPA_INET_H@
#cmakedefine TIME_WITH_SYS_TIME @TIME_WITH_SYS_TIME@

#cmakedefine HAVE_SYSLOG_FAC_NAMES @HAVE_SYSLOG_FAC_NAMES@
#cmakedefine HAVE_SYSLOG_PRI_NAMES @HAVE_SYSLOG_PRI_NAMES@
#cmakedefine CURS_HAVE_MVVLINE @CURS_HAVE_MVVLINE@

#cmakedefine TCP_SPEED @TCP_SPEED@
#cmakedefine DEFAULT_SPEED @DEFAULT_SPEED@
#cmakedefine MAX_STRING @MAX_STRING@
#cmakedefine MAX_NODELIST @MAX_NODELIST@
#cmakedefine CONFIG "@CONFIG@"
#cmakedefine PACKAGE_NAME "@PACKAGE_NAME@"
#cmakedefine PACKAGE_VERSION "@PACKAGE_VERSION@"

#cmakedefine WITH_PERL @WITH_PERL@
